### ISSUE TITLE
Current Squash implementation makes division by zero possible.

### ISSUE THREAD

**Issue by 0xpantera** [Francososa/ai_lab_gt_capsNet#2]
The norm of a vector of size 0 is 0, if at least one of the vectors is of size 0, the second term of the equation will be a division by zero. We could add a small epsilon value to the denominator, however all other implementations seem to implement a much more convoluted solution.

**Comment by sebasibarguen** [comment]
This is true, although it would be in a rare occasion where the vector norm is 0.  It would mean that the all the values in the vector are 0.

**Comment by 0xpantera** [comment]
Fair enough. Let's merge. If we start getting `inf.` as results we'll know the reason. I could also right some tests to warn if this happens. Any objections, before I merge?
